import { Patient } from "../types/patient";

// 18 synthetic patients. Deliberately spans High / Medium / Low risk tiers
// (5 each) plus 3 cold-start patients (< 2 recorded appointments) so the
// dashboard demonstrates every rendering path out of the box.
export const seedPatients: Patient[] = [
  // --- High risk (5) ---
  {
    id: "P001",
    name: "Meena Iyer",
    email: "meena.iyer@example-mail.com",
    age: 70,
    distanceKm: 45,
    totalAppointmentCount: 10,
    missedAppointmentCount: 7,
    daysSinceLastVisit: 50,
    expectedFrequencyDays: 14,
    treatmentElapsedDays: 170,
    treatmentTotalDays: 200,
  },
  {
    id: "P002",
    name: "Suresh Nair",
    email: "suresh.nair@example-mail.com",
    age: 66,
    distanceKm: 30,
    totalAppointmentCount: 9,
    missedAppointmentCount: 5,
    daysSinceLastVisit: 33,
    expectedFrequencyDays: 21,
    treatmentElapsedDays: 60,
    treatmentTotalDays: 80,
  },
  {
    id: "P003",
    name: "Kavitha Raman",
    email: "kavitha.raman@example-mail.com",
    age: 68,
    distanceKm: 50,
    totalAppointmentCount: 6,
    missedAppointmentCount: 4,
    daysSinceLastVisit: 45,
    expectedFrequencyDays: 30,
    treatmentElapsedDays: 40,
    treatmentTotalDays: 100,
  },
  {
    id: "P004",
    name: "Vikram Singh",
    email: "vikram.singh@example-mail.com",
    age: 29,
    distanceKm: 25,
    totalAppointmentCount: 8,
    missedAppointmentCount: 6,
    daysSinceLastVisit: 10,
    expectedFrequencyDays: 10,
    treatmentElapsedDays: 90,
    treatmentTotalDays: 100,
  },
  {
    id: "P005",
    name: "Priya Nambiar",
    email: "priya.nambiar@example-mail.com",
    age: 50,
    distanceKm: 5,
    totalAppointmentCount: 9,
    missedAppointmentCount: 8,
    daysSinceLastVisit: 70,
    expectedFrequencyDays: 20,
    treatmentElapsedDays: 20,
    treatmentTotalDays: 120,
  },

  // --- Medium risk (5) ---
  {
    id: "P006",
    name: "Anitha Krishnan",
    email: "anitha.krishnan@example-mail.com",
    age: 33,
    distanceKm: 22,
    totalAppointmentCount: 10,
    missedAppointmentCount: 3,
    daysSinceLastVisit: 21,
    expectedFrequencyDays: 14,
    treatmentElapsedDays: 30,
    treatmentTotalDays: 100,
  },
  {
    id: "P007",
    name: "Ganesh Pillai",
    email: "ganesh.pillai@example-mail.com",
    age: 62,
    distanceKm: 45,
    totalAppointmentCount: 8,
    missedAppointmentCount: 2,
    daysSinceLastVisit: 18,
    expectedFrequencyDays: 21,
    treatmentElapsedDays: 55,
    treatmentTotalDays: 90,
  },
  {
    id: "P008",
    name: "Rukmini Bhat",
    email: "rukmini.bhat@example-mail.com",
    age: 67,
    distanceKm: 18,
    totalAppointmentCount: 11,
    missedAppointmentCount: 4,
    daysSinceLastVisit: 28,
    expectedFrequencyDays: 20,
    treatmentElapsedDays: 40,
    treatmentTotalDays: 130,
  },
  {
    id: "P009",
    name: "Dinesh Rao",
    email: "dinesh.rao@example-mail.com",
    age: 45,
    distanceKm: 28,
    totalAppointmentCount: 14,
    missedAppointmentCount: 5,
    daysSinceLastVisit: 34,
    expectedFrequencyDays: 30,
    treatmentElapsedDays: 70,
    treatmentTotalDays: 140,
  },
  {
    id: "P010",
    name: "Latha Menon",
    email: "latha.menon@example-mail.com",
    age: 29,
    distanceKm: 10,
    totalAppointmentCount: 11,
    missedAppointmentCount: 6,
    daysSinceLastVisit: 16,
    expectedFrequencyDays: 21,
    treatmentElapsedDays: 50,
    treatmentTotalDays: 110,
  },

  // --- Low risk (5) ---
  {
    id: "P011",
    name: "Manoj Varma",
    email: "manoj.varma@example-mail.com",
    age: 40,
    distanceKm: 8,
    totalAppointmentCount: 10,
    missedAppointmentCount: 1,
    daysSinceLastVisit: 12,
    expectedFrequencyDays: 14,
    treatmentElapsedDays: 10,
    treatmentTotalDays: 100,
  },
  {
    id: "P012",
    name: "Divya Suresh",
    email: "divya.suresh@example-mail.com",
    age: 25,
    distanceKm: 5,
    totalAppointmentCount: 6,
    missedAppointmentCount: 0,
    daysSinceLastVisit: 10,
    expectedFrequencyDays: 20,
    treatmentElapsedDays: 15,
    treatmentTotalDays: 60,
  },
  {
    id: "P013",
    name: "Bhaskar Reddy",
    email: "bhaskar.reddy@example-mail.com",
    age: 50,
    distanceKm: 30,
    totalAppointmentCount: 9,
    missedAppointmentCount: 2,
    daysSinceLastVisit: 19,
    expectedFrequencyDays: 21,
    treatmentElapsedDays: 20,
    treatmentTotalDays: 100,
  },
  {
    id: "P014",
    name: "Shanti Devi",
    email: "shanti.devi@example-mail.com",
    age: 70,
    distanceKm: 15,
    totalAppointmentCount: 7,
    missedAppointmentCount: 1,
    daysSinceLastVisit: 16,
    expectedFrequencyDays: 18,
    treatmentElapsedDays: 25,
    treatmentTotalDays: 120,
  },
  {
    id: "P015",
    name: "Naveen Kumar",
    email: "naveen.kumar@example-mail.com",
    age: 33,
    distanceKm: 12,
    totalAppointmentCount: 12,
    missedAppointmentCount: 0,
    daysSinceLastVisit: 8,
    expectedFrequencyDays: 14,
    treatmentElapsedDays: 10,
    treatmentTotalDays: 200,
  },

  // --- Cold start (3) — fewer than 2 recorded appointments ---
  {
    id: "P016",
    name: "Ajay Menon",
    email: "ajay.menon@example-mail.com",
    age: 28,
    distanceKm: 10,
    totalAppointmentCount: 0,
    missedAppointmentCount: 0,
    daysSinceLastVisit: 0,
    expectedFrequencyDays: 14,
    treatmentElapsedDays: 0,
    treatmentTotalDays: 90,
  },
  {
    id: "P017",
    name: "Fathima Beevi",
    email: "fathima.beevi@example-mail.com",
    age: 55,
    distanceKm: 20,
    totalAppointmentCount: 1,
    missedAppointmentCount: 0,
    daysSinceLastVisit: 5,
    expectedFrequencyDays: 21,
    treatmentElapsedDays: 5,
    treatmentTotalDays: 100,
  },
  {
    id: "P018",
    name: "Karthik Subramanian",
    email: "karthik.subramanian@example-mail.com",
    age: 60,
    distanceKm: 35,
    totalAppointmentCount: 1,
    missedAppointmentCount: 1,
    daysSinceLastVisit: 30,
    expectedFrequencyDays: 20,
    treatmentElapsedDays: 10,
    treatmentTotalDays: 80,
  },
];
